packaging_format = 2

id = "pandora"
name = "Pandora IoT"
description.en = "IoT sensor API and demo AI prediction service for agriculture."
description.tr = "Tarımsal kullanım için IoT sensör API'si ve demo AI tahmin servisi."
version = "1.0.0~ynh1"
maintainers = ["SyewaN"]

[upstream]
license = "MIT"
code = "https://github.com/SyewaN/pandora"
admindoc = "https://github.com/SyewaN/pandora"
userdoc = "https://github.com/SyewaN/pandora"

[integration]
yunohost = ">= 11.1"
helpers_version = "2.0"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1G"
ram.build = "1G"
ram.runtime = "700M"

[install]
[install.domain]
type = "domain"

[install.path]
type = "path"
default = "/pandora"

[install.init_main_permission]
type = "group"
default = "visitors"

[install.repo_url]
ask.en = "Git repository URL to deploy"
ask.tr = "Deploy edilecek Git repository URL'i"
type = "url"
default = "https://github.com/SyewaN/pandora.git"

[install.repo_branch]
ask.en = "Git branch or tag"
ask.tr = "Git branch veya tag"
type = "string"
default = "main"

[resources]
[resources.permissions]
main.url = "/dashboard"
